export default {
  REDUXFORM: {
    CHANGE: '@@redux-form/CHANGE',
    FOCUS: '@@redux-form/FOCUS',
    BLUR: '@@redux-form/BLUR',
  },
  ONBOARDING: {
    TOGGLE_TOOLTIP: 'ONBOARDING.TOGGLE_TOOLTIP',
    SET_NEXT_STEP: 'ONBOARDING.SET_NEXT_STEP',
  },
  PREONBOARDING: {
    CHANGE_ACTIVE_TAB: 'PREONBOARDING.CHANGE_ACTIVE_TAB',
    CONTINUE: 'PREONBOARDING.CONTINUE',
  },
  NOTIFICATION: {
    SHOW: 'NOTIFICATION.SHOW',
    DISMISS: 'NOTIFICATION.DISMISS',
  },
};
