export default {
  NOTIFICATION: {
    SHOW: 'NOTIFICATION.SHOW',
    DISMISS: 'NOTIFICATION.DISMISS',
  },
  LOGIN: {
    SUCCESS: 'LOGIN.SUCCESS',
  },
  REFRESH: {
    SUCCESS: 'REFRESH.SUCCESS',
  },
};
